linters:
  enable:
    - dogsled
    - err113
    - exhaustive
    - gci
    - godot
    - gofmt
    - grouper
    - lll
    - mirror
    - misspell
    - mnd
    - predeclared
    - reassign
    - revive
    - tagliatelle
    - unused
    - wsl

run:
  timeout: 3m
  issues-exit-code: 1

output:
  formats:
    - format: tab
  print-issued-lines: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: "migrations/"
      linters:
        - gofmt
